### ISSUE TITLE
服务端还能提供下吗

### ISSUE THREAD

**Issue by fancierpj0** [wjkang/d2-admin-pm#7]
https://github.com/wjkang/d2-admin-serve 没了呢QAQ

**Comment by lwydyby** [comment]
> https://github.com/wjkang/d2-admin-serve 没了呢QAQ

我用springboot做了个服务端 https://github.com/lwydyby/springboot-cli-server

**Comment by wjkang** [comment]
https://github.com/wjkang/d2-admin-server
